transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToPILImage
    - _target_: torchvision.transforms.RandomCrop
      size: [448, 448] # [h,w] Min size of actual tiles
    - _target_: torchvision.transforms.Resize
      size: [224, 224]
    - _target_: torchvision.transforms.RandAugment
      num_ops: 4
      magnitude: 19
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
